## Loading data set

In [2]:
# Import the pandas library as pd for data manipulation
import pandas as pd

# Import the numpy library as np for numerical operations
import numpy as np 

# Import the seaborn library as sns for stastical data visualization
import seaborn as sns

# Import the matplotlib.pyplot module as plt for plotting graphs and visualization
import matplotlib.pyplot as plt

# Import warnings module to supress any warnings that might occurs during code executions 
import warnings 

# Supress warnings to improvr code readability
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv("data\primevideo_india_movies_and_shows.csv")

df.head()

,showid,name,season,type,imdb_rating,runtime,episode_count,release_year,rating,uhd,...,genre,moods,synopsis,content_advisory,audio_languages,subtitles,directors,producers,starring,studio
0,0PDOKMV9CRLOMO5EUKNCUJLG4Q,Mirzapur,Season 1,TV Show,8.5,7.1166,9.0,2018.0,A,True,...,Suspense;Action;Drama,NaN,The iron-fisted Akhandanand Tripathi is a mill...,Alcohol use;substance use;sexual content;viole...,हिन्दी [ऑडियो विवरण];தமிழ்;हिन्दी;తెలుగు,English;हिन्दी [CC];தமிழ்;తెలుగు,Gurmmeet Singh;Mihir Desai;Karan Anshuman;Anan...,Farhan Akhtar;Kassim Jagmagia;Abbas Raza Khan;...,Ali Fazal;Vikrant Massey;Pankaj Tripathi,Amazon Studios
1,0S3QYI59BAEI5KVLHCKSR91YGD,The Family Man,Season 1,TV Show,8.7,7.5167,10.0,2019.0,A,False,...,Comedy;Drama;Action,NaN,"The Family Man is an edgy action-drama series,...",Alcohol use;substance use;sexual content;viole...,Hindi,None available,Raj and DK,Raj and DK,Manoj Bajpayee;Priyamani;Sharib Hashmi,Amazon Studios
2,0K1PD4TOMOSBMIDEZ8Q04QDQ51,Aspirants,Season 1,TV Show,9.2,3.6167,5.0,2021.0,A,True,...,Drama,NaN,It is the story of the journey of three UPSC A...,Violence;foul language;alcohol use;tobacco dep...,தமிழ்;हिन्दी;తెలుగు,English,Apoorv Singh Karki,Arunabh Kumar,Naveen Kasturia;Shivankit Singh Parihar;Abhila...,The Viral Fever
3,0HDHQAUF5LPWOJRCO025LFJSJI,Farzi,Season 1,TV Show,NaN,7.4499,8.0,2023.0,A,True,...,Drama;Suspense,NaN,"Sunny, a brilliant small-time artist is catapu...",Violence;sexual content;foul language;alcohol ...,हिन्दी [ऑडियो विवरण];ಕನ್ನಡ;தமிழ்;हिन्दी;తెలుగు...,English;हिन्दी [CC];ಕನ್ನಡ;മലയാളം;தமிழ்;తెలుగు,Raj & DK,Raj & DK,Shahid Kapoor;Vijay Sethupathi;Kay Kay Menon,Amazon Studios
4,0P5ROL29KLRVMWUJ83F66Z5F38,Dry Day,NaN,Movie,NaN,2.1333,NaN,2023.0,A,True,...,Comedy;Drama,NaN,When his wife makes a vow to abort their baby ...,Violence;sexual content;foul language;alcohol ...,हिन्दी [ऑडियो विवरण];हिन्दी,English;हिन्दी [CC],Saurabh Shukla,Monisha Advani;Madhu Bhojwani;Nikkhil Advani,Jitendra Kumar;Shriya Pilgaonkar;Annu Kapoor,Amazon Studios

In [4]:
df.tail()

,showid,name,season,type,imdb_rating,runtime,episode_count,release_year,rating,uhd,...,genre,moods,synopsis,content_advisory,audio_languages,subtitles,directors,producers,starring,studio
9462,0TRCE1XYD8WND2GSCXWS96KBZU,Exorcist II: The Heretic,NaN,Movie,NaN,1.9500,NaN,1977.0,A,False,...,Horror,Dark;Frightening;Sophisticated,"It is 4 years since Regan s exorcism, and some...",Violence;sexual content;foul language;nudity;f...,English,English [CC],John Boorman,John Boorman Richard Lederer,Linda Blair Richard Burton Louise Fletcher Max...,Warner Bros.
9463,0QOMJNKQOEXVKHX0KSJCTFDY0D,The A-Team,NaN,Movie,NaN,1.9667,NaN,2010.0,U/A 16+,False,...,Adventure;Suspense,Compelling;Thrilling,Former Special Forces soldiers use their uniqu...,Violence;sexual content;foul language;alcohol ...,English [Audio Description];English,English [CC],Joe Carnahan,Stephen J. Cannell;Spike Seldin;Tony Scott;Jul...,Liam Neeson;Bradley Cooper;Jessica Biel,Universal Studios
9464,0FFN25HQXRZ18KKX3P0PCGJS2E,Laakhon Mein Ek,Season 2,TV Show,NaN,3.7501,8.0,2019.0,A,False,...,International,NaN,Dr Shreya is posted in Sitlapur village to con...,Alcohol use;violence;tobacco depictions;foul l...,தமிழ்;हिन्दी;తెలుగు,English (UK) [CC];English (US),Abhishek Sengupta,OML Production,Shweta Tripathi Sharma;Sandeep Mehta;Suyash Joshi,OML
9465,0J4UI0O0SYFCX8XIM4W7QC46BN,Vettri Vizhaa,NaN,Movie,NaN,2.4167,NaN,1989.0,U,False,...,Action;Drama;Suspense,NaN,A wounded man finds himself in an unknown plac...,Suitable for all ages,Tamil,English [CC],Prathap K. Pothen,Santhi Narayanaswamy;T. Manohar,Kamal Haasan;Prabhu;Khushbu,Video Park
9466,0FO659YXNORWMMA4HK9FJWG4HR,Prem Qaidi,NaN,Movie,NaN,2.6000,NaN,1991.0,U,False,...,Action;Romance,NaN,"A teenage couple fall in love, but their relat...",Suitable for all ages,Hindi,English [CC],K. Muralimohana Rao,D. Ramanaidu,Karisma Kapoor;Harish;Paresh Rawal,Hi 5 Entertainments LLP

### Data Wrangling Process

In [5]:
# Check the shape of the DataFrame
print("Number of rows : ", df.shape[0])
print("Number of columns : ",df.shape[1])

print(df.shape)

Number of rows :  9467
Number of columns :  22
(9467, 22)

In [6]:
# print the column of the Dataframe 


print("Column Name : ", df.columns)
print("Column Name in List: ", df.columns.tolist())

Column Name :  Index(['showid', 'name', 'season', 'type', 'imdb_rating', 'runtime',
       'episode_count', 'release_year', 'rating', 'uhd', 'availability',
       'rent', 'genre', 'moods', 'synopsis', 'content_advisory',
       'audio_languages', 'subtitles', 'directors', 'producers', 'starring',
       'studio'],
      dtype='object')
Column Name in List:  ['showid', 'name', 'season', 'type', 'imdb_rating', 'runtime', 'episode_count', 'release_year', 'rating', 'uhd', 'availability', 'rent', 'genre', 'moods', 'synopsis', 'content_advisory', 'audio_languages', 'subtitles', 'directors', 'producers', 'starring', 'studio']

In [7]:
df.isnull().sum()

showid                 0
name                   0
season              7947
type                   0
imdb_rating         8702
runtime                0
episode_count       7976
release_year          43
rating                 0
uhd                    0
availability           0
rent                6213
genre                 14
moods               2585
synopsis               0
content_advisory       9
audio_languages       18
subtitles              0
directors            283
producers           1047
starring             307
studio               408
dtype: int64

In [10]:
# Fill missing values in the 'IMDb Rating' column with the mode (most frequent value)
# This ensures that missing IMDb ratings are replaced with a valid value

df['imdb_rating'].fillna(df['imdb_rating'].mode()[0],inplace=True)

# Fill missing values in the 'Year of Release' column with the mode (most frequent value)
# This ensures that missing release years are replaced with a valid value

df["release_year"].fillna(df['release_year'].mode()[0], inplace=True)

# Replace missing values in the 'Plot' column with 'No Data'
# This ensures that missing plot information is replaced with a placeholder

df["rent"].replace(np.nan, "No Data", inplace=True)

In [12]:
# Check for missing values in each column of the cleaned DataFrame df_prime
# After cleaning, there should be no missing values in any column

cleaning_missing_values = df.isnull().sum()

# Print the number of missing values for each column after cleaning
print("Missing values after cleaning")
print(cleaning_missing_values)

Missing values after cleaning
showid                 0
name                   0
season              7947
type                   0
imdb_rating            0
runtime                0
episode_count       7976
release_year           0
rating                 0
uhd                    0
availability           0
rent                   0
genre                 14
moods               2585
synopsis               0
content_advisory       9
audio_languages       18
subtitles              0
directors            283
producers           1047
starring             307
studio               408
dtype: int64